plugins {
    id 'idea'
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev.legacyforge' version '2.0.115'
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

version = "${minecraft_version}-${mod_loader}-${mod_version}"
group = "${mod_group_id}"

base {
    archivesName = mod_id
}

// Mojang ships Java 17 to end users in 1.18+, so your mod should target Java 17.
java.toolchain.languageVersion = JavaLanguageVersion.of(17)

legacyForge {
    // Specify the version of MinecraftForge to use.
    version = project.minecraft_version + '-' + project.forge_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    // This line is optional. Access Transformers are automatically detected
     accessTransformers = project.files('src/main/resources/META-INF/accesstransformer.cfg')

    // Default run configurations.
    // These can be tweaked, removed, or duplicated as needed.
    runs {
        client {
            client()

            // Comma-separated list of namespaces to load gametests from. Empty = all namespaces.
                programArguments.addAll("--username", "Dev")
            systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()
            systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
        }

        // This run config launches GameTestServer and runs all registered gametests, then exits.
        // By default, the server will crash when no gametests are provided.
        // The gametest system is also enabled by default for other run configs under the /test command.
        gameTestServer {
            type = "gameTestServer"
            systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
        }

        data {
            data()

            // example of overriding the workingDirectory set in configureEach above, uncomment if you want to use it
            // gameDirectory = project.file('run-data')

            // Specify the modid for data generation, where to output the resulting resource, and where to look for existing resources.
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            systemProperty 'forge.logging.console.level', 'debug'
            //mixin
            systemProperty 'mixin.verbose', 'true'
            systemProperty 'mixin.export', 'true'
            systemProperty 'mixin.dumpTargetOnFailure', 'true'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        // define mod <-> source bindings
        // these are used to tell the game which sources are for which mod
        // mostly optional in a single mod project
        // but multi mod projects should define one per mod
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    exclusiveContent {
        forRepository {
            maven {
                url "https://cursemaven.com"
            }
        }
        filter {
            includeGroup "curse.maven"
        }
    }
    maven { url 'https://maven.blamejared.com' }
    flatDir {
        dir 'libs'
    }
    maven {
        // location of the maven that hosts JEI files since January 2023
        name = "Jared's maven"
        url = "https://maven.blamejared.com/"
    }

    maven {
        url "https://maven.architectury.dev/"
    }
    maven {
        url "https://maven.latvian.dev/releases"
    }
    maven {
        name = "Flemmli97"
        url = "https://maven.blazing-coop.net/releases"
    }
    maven {
        url "https://maven.tterrag.com/"
    }

}

configurations {
    runtimeClasspath.extendsFrom localRuntime
}
obfuscation {
    createRemappingConfiguration(configurations.localRuntime)
}

mixin {
    add sourceSets.main, "${mod_id}.refmap.json"
    config "mixins.${mod_id}.json"
}

dependencies {
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'

    modImplementation "com.tterrag.registrate:Registrate:${registrate_version}"
    if (rootMod.toBoolean()) {
        jarJar(group: 'com.tterrag.registrate', name: 'Registrate', version: "[MC1.20,MC1.21)")
    }
}

jar {
    manifest.attributes([
            "MixinConfigs": "mixins.${mod_id}.json"
    ])
}

tasks.withType(ProcessResources).configureEach {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
    options.compilerArgs += [
            "-AoutRefMapFile=${buildDir}/resources/main/${mod_id}.refmap.json",
            "-AdefaultObfuscationEnv=searge"
    ]
}


dependencies {
    // L2
    modImplementation(jarJar("dev.xkmc.l2library:l2library:${l2library_version}-slim")) {
        transitive = false
    }
    modImplementation(jarJar("dev.xkmc.l2serial:l2serial:1.2.2")) {
        transitive = false
    }
    modImplementation(jarJar("dev.xkmc.l2tabs:l2tabs:0.3.3")) {
        transitive = false
    }

    modCompileOnly "mezz.jei:jei-${minecraft_version}-common-api:${jei_version}"
    modCompileOnly "mezz.jei:jei-${minecraft_version}-forge-api:${jei_version}"
    modImplementation "mezz.jei:jei-${minecraft_version}-forge:${jei_version}"
    modCompileOnly "vazkii.patchouli:Patchouli:1.20." +
            "1-84.1-FORGE:api"
    modImplementation "vazkii.patchouli:Patchouli:1.20.1-84.1-FORGE"

    modImplementation "curse.maven:caelus-308989:5281700"
    modImplementation "curse.maven:geckolib-388172:6333474"

    modImplementation "curse.maven:curios-309927:6418456"
    modImplementation "curse.maven:playeranimator-658587:4587214"

    modImplementation "curse.maven:irons-spells-n-spellbooks-855414:7402504"
    // Lionfish Api
    /*modImplementation "curse.maven:lionfish-api-1001614:5922047"*/

    // Embeddium
    modImplementation "curse.maven:embeddium-908741:5681725"

    // Oculus
    modImplementation "curse.maven:oculus-581495:6020952"

    // Better Brightness Slider
    modImplementation "curse.maven:better-brightness-slider-685037:4656287"

    // 玉
    modImplementation "curse.maven:jade-324717:6855440"

    // Better Combat
    modImplementation "curse.maven:better-combat-by-daedelus-639842:7287334"

    // playerAnimator
    modImplementation "curse.maven:playeranimator-658587:4587214"

    // Cloth Config API
    modImplementation "curse.maven:cloth-config-348521:5729105"

    // 试验假人
    modImplementation "curse.maven:mmmmmmmmmmmm-225738:6860192"

    // Moonlight Lib
    modImplementation "curse.maven:selene-499980:7027387"

    // kubejs
    modImplementation "dev.architectury:architectury-forge:${architectury_version}"
    modImplementation "dev.latvian.mods:rhino-forge:${rhino_version}"
    modImplementation "dev.latvian.mods:kubejs-forge:${kubejs_version}"

    // 怪物大乱斗
    modImplementation "io.github.flemmli97:mobbattle:${minecraft_version}-2.5.3-${mod_loader}"

    //游戏内账号切换
    modRuntimeOnly "curse.maven:in-game-account-switcher-232676:5457030"

    //自定义局域网联机
    modRuntimeOnly "curse.maven:lan-server-properties-387365:4776657"

    //nbt编辑器
    modRuntimeOnly "curse.maven:nbtedit-reborn-678133:5984630"
}


var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
            minecraft_version        : minecraft_version,
            minecraft_version_range  : minecraft_version_range,
            forge_version            : forge_version,
            forge_version_range      : forge_version_range,
            loader_version_range     : loader_version_range,
            mod_id                   : mod_id,
            mod_name                 : mod_name,
            mod_license              : mod_license,
            mod_version              : mod_version,
            mod_authors              : mod_authors,
            mod_description          : mod_description
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}
// Include the output of "generateModMetadata" as an input directory for the build
// this works with both building through Gradle and the IDE.
sourceSets.main.resources.srcDir generateModMetadata
// To avoid having to run "generateModMetadata" manually, make it run on every project reload
legacyForge.ideSyncTask generateModMetadata


// Example configuration to allow publishing using the maven-publish plugin
publishing {
    publications {
        register('mavenJava', MavenPublication) {
            artifact jar
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/mcmodsrepo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
    options.compilerArgs.add('-Xlint:-deprecation')
    options.compilerArgs.add('-Xlint:-removal')
}
